"use client";

import { RiAddLine, RiCloudLine, RiFileList3Line, RiFundsLine, RiLineChartLine, RiMoneyDollarCircleLine, RiRefreshLine, RiSafe2Line } from "react-icons/ri";
import { ArcGauge } from "@/components/charts/arc-gauge";
import { LazyPortfolioAreaChart } from "@/components/charts/lazy-portfolio-area-chart";
import { Sparkline } from "@/components/charts/sparkline";
import { MarketSourceLabel } from "@/components/market/market-source-label";
import { Reveal } from "@/components/animation/reveal";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { KpiIcon } from "@/components/ui/kpi-icon";
import { Progress } from "@/components/ui/progress";
import { SensitiveValue } from "@/components/ui/sensitive-value";
import { useDashboardMetrics } from "@/hooks/use-dashboard-metrics";
import { formatMoney, formatPercent, formatSignedMoney, formatSignedPercent, toPersianDate } from "@/lib/format";
import { incomePlanProgress } from "@/lib/plan-execution";
import type { AllocationRule, AppSettings, Asset, GoalFund, IncomeEvent, InvestmentTransaction, MarketQuote, MarketSnapshot, MoneyUnit, PlanItem } from "@/lib/types";
import { cn } from "@/lib/utils";

export function DashboardSection({ settings, rule, incomes, funds, assets, transactions, quotes, snapshots, marketMode, marketDegraded, marketLoading, marketLastUpdated, marketWarning, planItems, onRefreshMarket, onNewMoney, onOpenInvestments, onOpenFunds }: {
  settings: AppSettings; rule?: AllocationRule; incomes: IncomeEvent[]; funds: GoalFund[]; assets: Asset[]; transactions: InvestmentTransaction[]; quotes: MarketQuote[]; snapshots: MarketSnapshot[]; marketMode: string; marketDegraded?: boolean; marketLoading: boolean; marketLastUpdated: string | null; marketWarning?: string; planItems?: PlanItem[]; onRefreshMarket: () => void; onNewMoney: () => void; onOpenInvestments: () => void; onOpenFunds: () => void;
}) {
  const unit = settings.displayUnit;
  const metrics = useDashboardMetrics({ rule, incomes, funds, assets, transactions, quotes });
  const { positions, portfolio, pricingIncomplete, pnl, pnlPct, monthIncome, monthIncomeCount, emergency, emergencyPct, futureFocusPct, chartData } = metrics;
  const planProgress = incomePlanProgress(planItems);
  const hasPortfolioHistory = chartData.some((row) => row.value > 0);

  return <div className="space-y-4 sm:space-y-5">
    <Reveal direction="down" step={1}><div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><div className="type-caption type-body-strong text-primary">نمای کلی</div><h1 className="mt-1 type-page-title">سلام، امروز پولت کجاست؟</h1><p className="mt-1 type-body text-muted-foreground">یک نگاه سریع به تصمیم‌های مالی، صندوق‌ها و بازار.</p></div><Button onClick={onNewMoney} size="lg" className="w-full sm:w-auto"><RiAddLine className="size-5" /> پول جدید دارم</Button></div></Reveal>

    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6">
      <Reveal hover step={2} className="sm:col-span-2 xl:col-span-2"><SummaryCard featured icon={<RiFundsLine />} label="سرمایه فعلی" value={formatMoney(portfolio, unit)} sub={pricingIncomplete ? "بخشی از ارزش با Snapshot یا fallback محاسبه شده" : pnl >= 0 ? `${formatPercent(pnlPct)} نسبت به بهای خرید` : `${formatPercent(Math.abs(pnlPct))} افت نسبت به بهای خرید`} positive={pnl >= 0} /></Reveal>
      <Reveal hover step={3}><SummaryCard icon={<RiLineChartLine />} iconTone={pnl > 0 ? "profit" : pnl < 0 ? "danger" : "neutral"} label={pnl > 0 ? "سود باز" : pnl < 0 ? "زیان باز" : "سود / زیان باز"} value={formatSignedMoney(pnl, unit)} sub={pricingIncomplete ? "بازده فعلی شامل fallback قیمتی است" : pnl > 0 ? "ارزش فعلی بالاتر از بهای خرید" : pnl < 0 ? "ارزش فعلی پایین‌تر از بهای خرید" : "سبد روی نقطه سر‌به‌سر است"} financialTone={pnl > 0 ? "profit" : pnl < 0 ? "loss" : undefined}/></Reveal>
      <Reveal hover step={4}><SummaryCard icon={<RiMoneyDollarCircleLine />} label="پول ورودی این ماه" value={formatMoney(monthIncome, unit)} sub={`${new Intl.NumberFormat("fa-IR").format(monthIncomeCount)} ورودی ثبت شده`} /></Reveal>
      <Reveal hover step={5}><SummaryCard icon={<RiSafe2Line />} label="حاشیه امن" value={emergency ? formatMoney(emergency.currentToman, unit) : "هنوز نساختی"} sub={emergency ? `${formatPercent(emergencyPct)} از هدف اضطراری` : "از بخش صندوق‌ها شروع کن"} positive /></Reveal>
      <Reveal hover step={6}><SummaryCard icon={<RiFileList3Line />} iconTone={planProgress.pct >= 80 ? "primary" : "neutral"} label="پایبندی به برنامه" value={formatPercent(planProgress.pct, 0)} sub={`${formatMoney(planProgress.executed, unit, true)} / ${formatMoney(planProgress.planned, unit, true)}`} positive={planProgress.pct >= 80} /></Reveal>
    </div>

    <div className="grid gap-4 xl:grid-cols-[1.05fr_1.95fr]">
      <Reveal step={6} className="h-full">
      <Card className="h-full overflow-hidden"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>قانون پول فعلی</CardTitle><p className="mt-1 type-caption text-muted-foreground">{rule?.name ?? "بدون قانون فعال"}</p></div><Badge>{rule?.preset === "custom" ? "شخصی" : "پیشنهادی"}</Badge></CardHeader><CardContent><div className="grid gap-4 sm:grid-cols-[210px_1fr] sm:items-center"><div className="mx-auto"><ArcGauge value={futureFocusPct} label="امنیت + رشد" size={190} stroke={23}/></div><div className="space-y-3">{rule && <><AllocationRow label="زندگی" value={rule.lifePct}/><AllocationRow label="امنیت" value={rule.safetyPct}/><AllocationRow label="رشد" value={rule.growthPct}/></>}</div></div></CardContent></Card></Reveal>
      <Reveal step={7} className="h-full"><Card className="h-full"><CardHeader className="flex flex-row items-start justify-between"><div><CardTitle>روند سرمایه واردشده</CardTitle><p className="mt-1 type-caption text-muted-foreground">جمع خالص خریدهای ثبت‌شده در شش ماه اخیر؛ بدون ساختن تاریخچه قیمت مصنوعی</p></div><Button variant="ghost" size="sm" onClick={onOpenInvestments}>جزئیات</Button></CardHeader><CardContent>{hasPortfolioHistory ? <LazyPortfolioAreaChart data={chartData} unit={unit}/> : <DashboardEmptyState icon={<RiLineChartLine />} title="نمودار بعد از اولین خرید شکل می‌گیرد" description="یک خرید یا دارایی قبلی ثبت کن تا روند سرمایه از داده واقعی خودت ساخته شود." />}</CardContent></Card></Reveal>
    </div>

    <Reveal step={7}><Card><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>بازارهای منتخب</CardTitle><div className="mt-1 flex flex-wrap items-center gap-2 type-caption text-muted-foreground"><RiCloudLine/><span>{marketMode === "live" ? marketDegraded ? "داده واقعی بازار؛ بعضی منابع ناقص" : "داده واقعی بازار" : marketMode === "offline" ? "آخرین داده واقعی ذخیره‌شده روی دستگاه" : marketMode === "unconfigured" ? "Provider بازار تنظیم نشده است" : "داده بازار در دسترس نیست"}</span>{marketLastUpdated && <span>· {new Intl.DateTimeFormat("fa-IR-u-ca-persian", { hour: "2-digit", minute: "2-digit", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date(marketLastUpdated))}</span>}{marketWarning && <span className="text-destructive">· {marketWarning}</span>}</div></div><Button variant="outline" size="icon" onClick={onRefreshMarket} disabled={marketLoading} aria-label="به‌روزرسانی قیمت بازار"><RiRefreshLine className={cn("size-4", marketLoading && "animate-spin")}/></Button></CardHeader><CardContent>{quotes.length ? <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4">{quotes.slice(0,4).map((q) => <MarketCard key={`${q.source}:${q.marketId ?? q.symbol}`} quote={q} unit={unit} snapshots={snapshots.filter((row) => q.marketId ? row.source === q.source && row.marketId === q.marketId : !row.marketId && row.symbol === q.symbol).slice(0, 24).reverse()}/>)}</div> : <DashboardEmptyState icon={<RiCloudLine />} title={marketLoading ? "در حال دریافت قیمت بازار..." : "قیمت بازار فعلاً در دسترس نیست"} description={marketMode === "unconfigured" ? "کلید Provider بازار را تنظیم کن؛ داده مالی شخصی برای دریافت قیمت ارسال نمی‌شود." : "آخرین داده معتبر حفظ می‌شود و می‌توانی دوباره تلاش کنی."} action={!marketLoading && marketMode !== "unconfigured" ? <Button variant="outline" size="sm" onClick={onRefreshMarket}><RiRefreshLine /> تلاش دوباره</Button> : undefined} />}</CardContent></Card></Reveal>

    <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]">
      <Reveal step={8} className="h-full">
      <Card className="h-full"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle>صندوق‌های هدف</CardTitle><p className="mt-1 type-caption text-muted-foreground">هزینه‌هایی که بهتر است قبل از رسیدنشان برایشان پول کنار بگذاری</p></div><Button variant="ghost" size="sm" onClick={onOpenFunds}>همه صندوق‌ها</Button></CardHeader><CardContent>{funds.length ? <div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{funds.slice(0,3).map((fund) => <FundPreview key={fund.id} fund={fund} unit={unit}/>)}</div> : <DashboardEmptyState icon={<RiSafe2Line />} title="هنوز صندوق هدفی نداری" description="برای هزینه‌های آینده یک صندوق بساز تا پیشرفت آن همیشه جلوی چشمت باشد." action={<Button variant="outline" size="sm" onClick={onOpenFunds}>ساخت اولین صندوق</Button>} />}</CardContent></Card></Reveal>
      <Reveal step={8} className="h-full"><Card className="soft-card h-full"><CardHeader><CardTitle>بینش این ماه</CardTitle></CardHeader><CardContent><div className="space-y-3 text-sm leading-7"><InsightDot>{emergency && emergencyPct < 100 ? `برای تکمیل صندوق اضطراری حدود ${formatMoney(Math.max(0, emergency.targetToman - emergency.currentToman), unit)} فاصله داری.` : "صندوق اضطراری در وضعیت مناسبی است."}</InsightDot><InsightDot>{pricingIncomplete ? "ارزش سبد برای نمایش حفظ شده، اما رتبه سهم دارایی‌ها تا قیمت قابل اتکا قطعی نیست." : positions.some((item) => item.currentValue > 0) ? `${positions.filter((item) => item.currentValue > 0).sort((a,b)=>b.currentValue-a.currentValue)[0].asset.name} بیشترین سهم ارزش فعلی سبد را دارد.` : "اولین خرید واقعی را ثبت کن تا تحلیل سبد شروع شود."}</InsightDot><InsightDot>{pricingIncomplete ? "تخصیص خودکار پول جدید تا برگشت قیمت تازه بازار یا قیمت دستی قابل اتکا متوقف است." : "پیشنهادهای پولم‌کو از «پول جدید» برای نزدیک‌شدن به تخصیص هدف استفاده می‌کنند."}</InsightDot></div></CardContent></Card></Reveal>
    </div>
  </div>;
}

function SummaryCard({ icon, iconTone = "primary", label, value, sub, positive, financialTone, featured }: { icon: React.ReactNode; iconTone?: "primary" | "profit" | "danger" | "neutral"; label: string; value: string; sub: string; positive?: boolean; financialTone?: "profit" | "loss"; featured?: boolean }) {
  return <Card className={cn("h-full", featured && "border-primary/15 ring-1 ring-primary/5")}><CardContent className={cn("p-4 sm:p-5", featured && "sm:p-6")}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="type-caption text-muted-foreground">{label}</div><SensitiveValue className={cn("mt-2 type-section-title tabular-nums sm:text-2xl", featured && "sm:text-3xl", financialTone === "profit" && "text-profit", financialTone === "loss" && "text-loss")}>{value}</SensitiveValue></div><KpiIcon tone={iconTone}>{icon}</KpiIcon></div><div className={cn("mt-3 text-[11px]", financialTone === "profit" ? "text-profit" : financialTone === "loss" || positive === false ? "text-loss" : "text-muted-foreground")}><SensitiveValue>{sub}</SensitiveValue></div></CardContent></Card>;
}
function DashboardEmptyState({ icon, title, description, action }: { icon: React.ReactNode; title: string; description: string; action?: React.ReactNode }) { return <div className="grid min-h-44 place-items-center rounded-2xl border border-dashed bg-muted/15 p-5 text-center"><div><div className="mx-auto grid size-10 place-items-center rounded-2xl bg-primary/8 text-primary [&_svg]:size-5">{icon}</div><div className="mt-3 type-strong">{title}</div><p className="mx-auto mt-1 max-w-md type-caption leading-6 text-muted-foreground">{description}</p>{action && <div className="mt-3 flex justify-center">{action}</div>}</div></div>; }
function AllocationRow({ label, value }: { label: string; value: number }) { return <div><div className="mb-1.5 flex justify-between text-xs"><span>{label}</span><SensitiveValue className="type-strong">{formatPercent(value,0)}</SensitiveValue></div><Progress value={value}/></div>; }
function MarketCard({ quote, unit, snapshots }: { quote: MarketQuote; unit: MoneyUnit; snapshots: MarketSnapshot[] }) { const snapshot = quote.runtimeSource === "snapshot"; const positive = quote.changePercent >= 0; const seed = snapshots.length > 1 ? snapshots.map((row) => row.priceToman) : [quote.priceToman, quote.priceToman]; return <div className="rounded-2xl border bg-background/60 p-3 transition-[transform,border-color,box-shadow] duration-200 hover:-translate-y-0.5 hover:border-primary/20 hover:shadow-sm motion-reduce:hover:translate-y-0"><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-1.5 type-caption text-muted-foreground"><span>{quote.name}</span></div><div className="mt-0.5 text-[9px] text-muted-foreground"><MarketSourceLabel source={quote.source} snapshot={snapshot} snapshotAt={quote.snapshotCapturedAt} /></div><SensitiveValue className="mt-1 type-strong">{formatMoney(quote.priceToman, unit, true)}</SensitiveValue><div className={cn("mt-1 text-[10px]", snapshot ? "text-muted-foreground" : positive ? "text-profit" : "text-loss")}>{snapshot ? "تغییر امروز تازه نیست" : <SensitiveValue>{formatSignedMoney(quote.changeValueToman, unit, true)} امروز</SensitiveValue>}</div></div><div className={cn("rounded-lg px-2 py-1 text-[10px] type-strong", snapshot ? "bg-muted text-muted-foreground" : positive ? "bg-profit/10 text-profit" : "bg-loss/10 text-loss")}>{snapshot ? "Snapshot" : <SensitiveValue>{formatSignedPercent(quote.changePercent)}</SensitiveValue>}</div></div><Sparkline data={seed} positive={snapshot ? true : positive}/></div>; }
function FundPreview({ fund, unit }: { fund: GoalFund; unit: MoneyUnit }) { const pct = fund.targetToman ? Math.min(100, fund.currentToman/fund.targetToman*100) : 0; return <div className="rounded-2xl border p-4 transition-[transform,border-color] duration-200 hover:-translate-y-0.5 hover:border-primary/20 motion-reduce:hover:translate-y-0"><div className="flex items-center justify-between gap-2"><strong className="text-sm">{fund.name}</strong><SensitiveValue className="text-xs type-strong text-primary">{formatPercent(pct,0)}</SensitiveValue></div><Progress value={pct} className="mt-3"/><div className="mt-3 flex justify-between text-[10px] text-muted-foreground"><SensitiveValue>{formatMoney(fund.currentToman, unit, true)}</SensitiveValue><span>{fund.dueAt ? toPersianDate(fund.dueAt) : "بدون موعد"}</span></div></div>; }
function InsightDot({ children }: { children: React.ReactNode }) { return <div className="flex gap-2"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-primary"/><span>{children}</span></div>; }
